<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoopingAudioConverter.PCM\LoopingAudioConverter.PCM.csproj" />
    <ProjectReference Include="..\LoopingAudioConverter.WAV\LoopingAudioConverter.WAV.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VGAudio">
      <HintPath>..\lib\VGAudio.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
